name: Node.js Package

on:
    push:
        branches:
            - "1.x_no_tests"
        tags:
            - v1*
        paths-ignore:
            - "docs/**"
            - "assets/**"
            - "**.md"
    pull_request:
        branches:
            - "1.x_no_tests"
        types: [opened, reopened, synchronize]
        paths-ignore:
            - "docs/**"
            - "assets/**"
            - "**.md"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12
            - run: npm ci

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
            - run: npm ci
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
